app/controllers/contents_controller.rb, app/views/contents/index.html.erb, app/views/feeds/_form.html.erb
- Fix crash when graphic content is submitted without an uploaded media
- Fix information leakage (only display data that user can access)
=> Housekeeping

config/initializers/00-inflections.rb, config/initializers/01-db_create_load_or_migrate.rb, config/initializers/02-concerto_config.rb, config/initializers/03-secret_token.rb, config/initializers/04-backtrace_silencers.rb, config/initializers/05-filter_parameter_logging.rb, config/initializers/06-mime_types.rb, config/initializers/07-devise.rb, config/initializers/08-session_store.rb, config/initializers/09-translated_languages.rb, config/initializers/10-wrap_parameters.rb, config/initializers/11-content_types.rb, config/initializers/12-plugins.rb, config/initializers/13-airbrake.rb, config/initializers/14-delayed_job_setup.rb, config/initializers/15-scrubbing_logger.rb, config/initializers/16-mailer.rb, config/initializers/17-required_data.rb, config/initializers/18-field_configs.rb, config/initializers/19-analytics.rb, config/initializers/20-kaminari_config.rb, config/initializers/21-assets.rb, config/initializers/99-remove_unused_config_entries.rb
Added the logging to those where it was missing, and also swapped devise and secret token initializers since the newer devise will need the token.
=> use __FILE__ for logging

app/views/screens/_show_body.html.erb, config/locales/de.yml, config/locales/en.yml, config/locales/fr.yml, config/locales/he.yml, config/locales/nl.yml, config/locales/views/screens/en.yml
reword field settings to close #1199
=> Better field setting description

app/controllers/application_controller.rb, app/controllers/feeds_controller.rb
=> Check for authentication plugins in non public Concerto instances

app/assets/stylesheets/application/components/tiles.scss.erb, app/views/submissions/_submission_tile.html.erb
fixes  https://github.com/concerto-addons/concerto_content_scheduling/issues/18
=> tile icon overlap fix

app/controllers/media_controller.rb
automatically orients images with rmagick based on their exif info.  could close #1231
=> auto orient jpegs

app/assets/stylesheets/frontend/application.css.scss
required for concerto/concerto-frontend#54 - provides font-awesome to screens
=> make font-awesomeness available to the frontend screens

app/models/ability.rb, app/views/contents/_show_details.html.erb, config/locales/views/contents/en.yml
fixes 1 through 3 of #1194.
Someone should think through the permission change and make sure it is acceptable.
=> resubmit content button and permission fixes

app/controllers/templates_controller.rb, app/views/templates/_form.html.erb, config/locales/views/templates/en.yml
If you have supplied a template with some custom css, you can now see what that custom css content is in case you want to tweak it or copy it to another template.
=> closes #1280 show templates custom css if any

app/views/public_activity/template/_copy.html.erb, config/locales/en.yml, lib/tasks/template.rake
Now you can run a rake task to copy a template!
```
rake template:copy["BlueSwoosh","PurpleRain"]
```
Very important to *not* have a space after the comma in the parameters or rake will get irritated.
```
rake template:copy[source_name,destination_name]  # copy a concerto template
```
=> add task to copy a concerto template

app/controllers/memberships_controller.rb, app/views/groups/manage_members.html.erb, app/views/public_activity/membership/_approve.html.erb, app/views/public_activity/membership/_demote.html.erb, app/views/public_activity/membership/_promote.html.erb, app/views/public_activity/membership/_update.html.erb, config/locales/en.yml
closes #1277 
Adds more pa logging by setting the pa key to the custom update action in the membership controller.
=> additional public activity for membership

app/models/dynamic_content.rb
This is required by the concerto_content_schedule/#25 plugin to allow dynamically generated childern to inherit the schedule set on the parent item.
=> provide hook for altering dynamic content

app/controllers/application_controller.rb, app/controllers/frontend/contents_controller.rb, app/controllers/frontend/screens_controller.rb
See #1286.  This should not impact any of @mikldt 's stuff, but getting his blessing on these changes would probably be a good idea.
=> expose ETag, and frontend cache key

app/controllers/templates_controller.rb, app/models/template.rb, app/views/templates/_show_header.html.erb, config/routes.rb, test/fixtures/fields.yml, test/fixtures/kinds.yml, test/unit/template_test.rb
@augustf check this out... (see export button on template show) with this puppy we could encourage users to share their custom templates on the forum.
=> ability to export template

app/views/contents/form_elements/_dates.html.erb
=> Use saved content start and end date/time while editing

app/controllers/groups_controller.rb, app/views/groups/_show_header.html.erb
=> Add badge with pending membership count to group's manage members button

app/assets/javascripts/graphics.js.erb, app/controllers/media_controller.rb, lib/concerto_image_magick.rb
It's a start towards #1313.  But we also need to display this somewhere when browsing the feed content...
=> display image size info

app/views/screens/_thumbs.html.erb
=> Change icon color when screen is online

app/assets/javascripts/content_resubmit.js, app/views/contents/_show_details.html.erb
=> Content resubmit tooltip

app/assets/javascripts/graphics.js.erb, app/views/contents/_form.html.erb, app/views/contents/_form_bottom.html.erb
=> Disable content submit until graphic upload is complete

app/controllers/frontend/contents_controller.rb, app/models/content.rb
This should solve the problem being reported on the forum.  Plus, this now considers the screen time when displaying content.  See comments in code below for impact.
=> display range timezone fix (and with regard to screen timezone)

app/assets/javascripts/graphics.js.erb, app/views/contents/_edit_form.html
=> fixes #1371 and #1373 content editing

app/models/concerto_plugin.rb
closes https://github.com/concerto-addons/concerto_template_scheduling/issues/20
closes https://github.com/concerto-addons/concerto_template_scheduling/issues/15
=> handle hooks with options

app/assets/javascripts/concerto_plugins.js, app/controllers/concerto_plugins_controller.rb
=> Gem upgrade capture stderr

config/initializers/01-db_create_load_or_migrate.rb
This fixes the occasional problem of redundant migration attempts. Closes #1303.
=> use native migrations check

app/models/feed.rb, app/models/group.rb
=> set default order to name for feeds and groups

app/views/groups/_feeds.html.erb, app/views/groups/_show_body.html.erb
=> dry up view, list groups feeds regardless of content

app/views/subscriptions/_subscription_tr.html.erb
=> subscriptions count active items per kind

app/views/dashboard/_browse.html.erb, app/views/feeds/_browse_body.html.erb, config/locales/en.yml
=> move submission notice to browse and add missing translation

app/views/submissions/_index_body.html.erb, config/locales/en.yml
=> list allowed types for each feed

app/models/dynamic_content.rb, app/views/submissions/index.html.erb
=> dynamic content should respect parent's end time

app/views/concerto_plugins/new.html.erb, app/views/contents/ticker/_render_default.html.erb
=> use new fa- prefix instead of old icon- prefix

db/migrate/20170525194137_make_content_data_larger.rb, db/schema.rb
=> allow more data in content

app/assets/stylesheets/frontend/application.css.scss
This resolves the pulsating scrollbar issue in #1449.
=> Hide scrollbars on frontend screens.

Dockerfile
The Dockerfile did not build successfully due to some packages being renamed, etc. I made some changes to get the image built successfully and have been able to run the Concerto container for testing without any issues.
=> Added additional packages to allow the image to be built successfully

db/migrate/20190911195651_increase_media_file_data_len.rb, db/schema.rb
Interesting how the other limits just popped up: https://github.com/rails/rails/issues/19001
=> specify limit for media file data so it can handle larger content

app/controllers/frontend/screens_controller.rb, app/controllers/screens_controller.rb, app/models/screen.rb, app/views/screens/_form.html.erb, db/migrate/20190920020204_add_locale_to_screen.rb, db/schema.rb
=> support screen locale for frontend

Dockerfile, docker-compose.yml, tools/nginx.docker.conf
upgrades to ruby 2.6, inprove dockerfile
=> tidy up dockerfile, upgrade to ruby 2.6
