app/views/feeds/moderate.html.erb
app/views/groups/_show_body.html.erb

- Another usage of ```count``` that ignored the ability / visible feeds by the user (count performs counting on database level which ignores cancan user abilities)
- Check if user can delete membership for showing leave group button

Permission / visibility fixes

---

app/controllers/application_controller.rb

template preview urls like templates/1/preview.png?height=450&width=800 do have image/png format which was not handled

fix ActionController::UnknownFormat for png files

---

app/models/ability.rb

fixes #1177 and #1174 
(The user rules themselves are meaningless because some lines above there is a rule that allows anybody to read all users, but that's another topic)

remove unnecessary block for cancan rules

---

app/models/template.rb
app/views/templates/_form.html.erb
app/views/templates/_show_body.html.erb

Fixes #1180.  Had to use reorder to override the ordering specified in the relation, and incorporated the md5 hash of the last modified field into the preview image for cache busting.

fix template preview image updating when it is modified

---

app/assets/javascripts/concerto_plugins.js

#1220 
Seems like the drop down menu value was still submitted when switching to the RubyGems text field. This caused two gem names to be submitted as pointed out in the original issue. I just added a quick change to disable the select input when using RubyGems as a source.

Disable concerto plugin select field when installing via rubygems

---

app/controllers/frontend/screens_controller.rb

This will add the UTC offset for the screen's time zone (in seconds and adjusting for DST) to the frontend setup.js. The frontend can then use this time offset to adjust the time field to match the screen's configured time zone.

Add screen's time zone UTC offset to frontend setup.js

---

app/controllers/frontend/screens_controller.rb

With the addition of momentjs to the new frontend, we can now just pass the time zone string instead of dealing with the UTC offset.

Update screen setup to include time zone string instead of offset

---

app/assets/javascripts/frontend/application.js
app/views/layouts/frontend.html.erb

This is related to concerto/concerto-frontend#47 but not dependent upon it.  From what I could tell, the screen_setup js was not being included in the frontend, so I don't think it was polling when a temp token was being used like it should have been.

include js in frontend

---

app/controllers/frontend/contents_controller.rb
app/controllers/frontend/screens_controller.rb
app/models/screen.rb

partial fix for concerto/concerto-frontend#50.  Includes media change detection and fixes a bug where passed arrays or associations were not having their updated_at property checked.

Frontend cache key update

---

app/controllers/concerto_config_controller.rb
app/mailers/activity_mailer.rb
config/locales/controllers/en.yml

A sample email is only sent if the mailer_from config field is not empty.

send sample email during configuration check

---

app/controllers/frontend/contents_controller.rb

This resolves the screen flicker caused by cached content holding a stale X-Concerto-Frontend-Setup-Key header value, by generating an ETag for each content.json request that consists of the value of the screen's frontend_cache_key plus the id's of the content in the payload (since content cannot actually change once it has been submitted, this should be sufficient).

fixes #1288 generate ETag for content

---

app/controllers/frontend/contents_controller.rb
lib/base_shuffle.rb
lib/weighted_shuffle.rb

This eliminates the concept of a store for timeline data, which was just going to the client anyway when cookie store was enabled. Instead, the entire timeline worth of content will be sent to the client. This timeline is not reliant on getting a cookie back which could have been overwritten in the client by a simultaneous request.
This will also have the side effects of reducing overall requests to the server, reducing the size of cookies that need to be sent to the server with each request, and reducing the overall number of queries from each screen for a given period of time.
If a reliable store for this data is found, the store concept could be reinstated. However the only reason for this would seem to be if the client could not store the whole timeline, which seems unlikely.
This …

Make frontend fields stateless to resolve repeating content issues.

---

app/assets/javascripts/concerto_plugins.js
app/controllers/concerto_plugins_controller.rb
app/views/concerto_plugins/show.html.erb
config/routes.rb

Addresses #1345 when upgrading a plugin... handles gem update async and provides more detailed feedback when bundle update fails or the assets precompile fails.  @augustf I changed the rake task to run from a system call so we could capture the output and success result-- don't know if that's a problem or not.  Seems to work fine for me in development, but a better test would be on a deployed environment.  
Please test this in your environments before you merge it.  Thanks.

plugin update feedback and alternate assets precompile

---

Gemfile
Gemfile.lock

This is where it was before the latest bundle update.

lock turbolinks at 2.5.3

---

app/views/screens/show.html.erb

I'd like to be able to display additional information via new plugins under the screen detail area.

add a view hook under the screen details

---

config/initializers/18-field_configs.rb

This adds a field setting which can be used with concerto/concerto-frontend#74

field config for supressing reload of repeat content

---

app/models/dynamic_content.rb

http://apidock.com/rails/ActiveRecord/Persistence/becomes
When loading new content, we were becoming the new class, but not persisting it which was causing problems when assigning attributes specific to the new class (like config). 
Also closes #1409

dynamic content - log error, persist derived class

---

app/models/dynamic_content.rb

This will allow other content to be refreshed, when the service runs, even if an entry fails.

dynamic content refresh exception handling

---

README.md
app/models/concerto_plugin.rb
lib/version_check.rb

These changes will prevent the application from erroring out when connection problems occur due to no internet connectivity.  However, to truly run your site isolated, you'll need to also set the `automatic_bundle_installation` and `airbrake_enabled_initially` settings in the config/concerto.yml to false, and make sure that your settings in the app indicate that you do not want to send errors to the developers.
The background job engine has been tested along with the website, and the concerto player.  
It almost goes without saying that dynamic content sourced from sites outside the isolated network will not be refreshed.
This change supports the scenario where a site (while connected to the internet) wants to bring the system online and install plugins and static content (and perhaps …

better handle when not connected to internet

---

app/models/template.rb
app/views/templates/_template.html.erb
config/locales/en.yml

list templates by name, include screen count

---

app/views/contents/form_elements/_dates.html.erb

If a piece of content is submitted without a start date or end date, screens subscribed to those feeds will throw 500 errors and not display _any_ content. Making these fields `required` with html5 makes the users not able to submit content with blank dates.

Make Start Date and End Date Required

---

app/models/text_content.rb
app/models/ticker.rb

This fixes #1466.  The bug was introduced back in March 6, 2017 when I DRYed up some code and extracted some common features in two classes into a new ancestor class, and accidentally included sanitizing the htmltext content where it wasn't happening before. (The simple-rss build_content already sanitizes it.)

revert - dont double sanitize htmltext

---

config/initializers/16-mailer.rb

ActionMailer user_name and password where being added into the Authentication key as an array (due to the additional commas). 
SMTP auth now working

Solve SMTP server connection when credentials used

---

app/views/concerto_plugins/show.html.erb
app/views/contents/show.html.erb
app/views/field_configs/index.html.erb
app/views/fields/edit.html.erb
app/views/groups/_show_header.html.erb
app/views/groups/manage_members.html.erb
app/views/kinds/index.html.erb
app/views/pages/index.html.erb
app/views/screens/_show_header.html.erb
app/views/submissions/_index_header.html.erb
app/views/submissions/_show_header.html.erb
app/views/templates/_show_header.html.erb
app/views/users/_show_header.html.erb
app/views/users/index.html.erb

Without sanitization, these are susceptible to an varying degrees of XSS attack depending on the input.  When the values are displayed in the twitter-bootstrap-confirmation modal (I don't fully understand how it works) the JS is rendered and executed. The `user.name` fields are the most concerning for instances that allow public registration, but we sanitize everywhere this pattern is used to be safe.
Kudos to Ben Shaw (@sudonoodle) for finding this vulnerability!

Sanitize keys before confirmation modal.

---

.travis.yml

@bamnet I checked, the fronted and the screen look fine. Is there a reason we didn't support 2.6 before?

use ruby 2.6

---

Gemfile.lock
docker-compose.yml

Concerto is currently using Ruby 2.6.10.  I tried setting it up under Docker to replace the VM-based installation my employer uses, but I got this error when I tried running it:
```/usr/local/rvm/rubies/ruby-2.6.10/lib/ruby/2.6.0/bundler/spec_set.rb:91:in `block in materialize': Could not find date-3.3.4 in any of the sources (Bundler::GemNotFound)```
According to https://stdgems.org/date/, date 3.3.4 needs Ruby 3.3.0 or later.  The version of date that is compatible with Ruby 2.6.10 is 2.0.3.  I edited Gemfile.lock, ran ```docker build -t concerto . && docker compose up``` again, and this time it came up with the "register first admin account" screen when I loaded it in my browser.
Also, ```--authentication-policy=mysql_native_password``` needs to be removed from docker-compose.yml, or …

Ruby 2.6.10 doesn't support date 3.3.4...use 2.0.3 instead
